-- MySQL Script generated by MySQL Workbench
-- Mon Jun 28 21:23:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Ifspdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Ifspdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ifspdb` DEFAULT CHARACTER SET utf8 ;
USE `Ifspdb` ;

-- -----------------------------------------------------
-- Table `Ifspdb`.`FrmConfComparecimeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ifspdb`.`FrmConfComparecimeto` (
  `idFrmConfComparecimeto` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `RG` VARCHAR(45) NULL,
  `Codigo` INT NULL,
  `Email` VARCHAR(45) NULL,
  `Data` DATE NULL,
  `Horario` TIME NULL,
  PRIMARY KEY (`idFrmConfComparecimeto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ifspdb`.`FrmDpalestras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ifspdb`.`FrmDpalestras` (
  `idFrmDpalestras` INT NOT NULL,
  `Palestrante` VARCHAR(45) NULL,
  `Tema` VARCHAR(45) NULL,
  `Local` VARCHAR(45) NULL,
  `Data` DATE NULL,
  `Horario` TIME NULL,
  `FrmConfComparecimeto_idFrmConfComparecimeto` INT NOT NULL,
  PRIMARY KEY (`idFrmDpalestras`),
  INDEX `fk_FrmDpalestras_FrmConfComparecimeto1_idx` (`FrmConfComparecimeto_idFrmConfComparecimeto` ASC) VISIBLE,
  CONSTRAINT `fk_FrmDpalestras_FrmConfComparecimeto1`
    FOREIGN KEY (`FrmConfComparecimeto_idFrmConfComparecimeto`)
    REFERENCES `Ifspdb`.`FrmConfComparecimeto` (`idFrmConfComparecimeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ifspdb`.`FrmCadAluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ifspdb`.`FrmCadAluno` (
  `idFrmCadAluno` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Cidade` VARCHAR(45) NULL,
  `Curso` VARCHAR(45) NULL,
  `Pontuario` VARCHAR(45) NULL,
  `AnoLetivo` YEAR(4) NULL,
  PRIMARY KEY (`idFrmCadAluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ifspdb`.`FrmCadPaletra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ifspdb`.`FrmCadPaletra` (
  `idFrmCadPaletra` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `RG` VARCHAR(45) NULL,
  `Cidade` VARCHAR(45) NULL,
  `Palestra` VARCHAR(45) NULL,
  `CodInscricao` INT NULL,
  `Data` DATE NULL,
  `Horario` TIME NULL,
  `Sala` VARCHAR(20) NULL,
  `FrmCadAluno_idFrmCadAluno` INT NOT NULL,
  PRIMARY KEY (`idFrmCadPaletra`),
  INDEX `fk_FrmCadPaletra_FrmCadAluno1_idx` (`FrmCadAluno_idFrmCadAluno` ASC) VISIBLE,
  CONSTRAINT `fk_FrmCadPaletra_FrmCadAluno1`
    FOREIGN KEY (`FrmCadAluno_idFrmCadAluno`)
    REFERENCES `Ifspdb`.`FrmCadAluno` (`idFrmCadAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ifspdb`.`Formulario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ifspdb`.`Formulario` (
  `idFormulario` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Mensagem` VARCHAR(500) NULL,
  PRIMARY KEY (`idFormulario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ifspdb`.`FrmEmissaoCertificado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ifspdb`.`FrmEmissaoCertificado` (
  `idFrmEmissaoCertificado` INT NOT NULL,
  `CodAcesso` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `FrmCadPaletra_idFrmCadPaletra` INT NOT NULL,
  `Formulario_idFormulario` INT NOT NULL,
  PRIMARY KEY (`idFrmEmissaoCertificado`, `FrmCadPaletra_idFrmCadPaletra`),
  INDEX `fk_FrmEmissaoCertificado_FrmCadPaletra1_idx` (`FrmCadPaletra_idFrmCadPaletra` ASC) VISIBLE,
  INDEX `fk_FrmEmissaoCertificado_Formulario1_idx` (`Formulario_idFormulario` ASC) VISIBLE,
  CONSTRAINT `fk_FrmEmissaoCertificado_FrmCadPaletra1`
    FOREIGN KEY (`FrmCadPaletra_idFrmCadPaletra`)
    REFERENCES `Ifspdb`.`FrmCadPaletra` (`idFrmCadPaletra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FrmEmissaoCertificado_Formulario1`
    FOREIGN KEY (`Formulario_idFormulario`)
    REFERENCES `Ifspdb`.`Formulario` (`idFormulario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ifspdb`.`FrmDcursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ifspdb`.`FrmDcursos` (
  `idFrmDcursos` INT NOT NULL,
  `Curso` VARCHAR(45) NULL,
  `CargaHoraria` TIMESTAMP(4) NOT NULL,
  `Local` VARCHAR(45) NULL,
  `Descricao` VARCHAR(500) NULL,
  PRIMARY KEY (`idFrmDcursos`, `CargaHoraria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ifspdb`.`FrmConfimarSala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ifspdb`.`FrmConfimarSala` (
  `idFrmConfimarSala` INT NOT NULL,
  `NomeInscrito` VARCHAR(45) NULL,
  `Sala` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Data` DATE NULL,
  `Horario` TIME NULL,
  `FrmDcursos_idFrmDcursos` INT NOT NULL,
  `FrmDcursos_CargaHoraria` TIMESTAMP(4) NOT NULL,
  PRIMARY KEY (`FrmDcursos_idFrmDcursos`, `FrmDcursos_CargaHoraria`),
  CONSTRAINT `fk_FrmConfimarSala_FrmDcursos1`
    FOREIGN KEY (`FrmDcursos_idFrmDcursos` , `FrmDcursos_CargaHoraria`)
    REFERENCES `Ifspdb`.`FrmDcursos` (`idFrmDcursos` , `CargaHoraria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ifspdb`.`FrmCadEnventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ifspdb`.`FrmCadEnventos` (
  `idFrmCadEnventos` INT NOT NULL,
  `NomeEventos` VARCHAR(45) NULL,
  `Data` DATE NULL,
  `Horario` TIME NULL,
  `CodEvento` INT NULL,
  PRIMARY KEY (`idFrmCadEnventos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ifspdb`.`FrmDeventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ifspdb`.`FrmDeventos` (
  `idFrmDeventos` INT NOT NULL,
  `NomeEventos` VARCHAR(45) NULL,
  `Data` DATE NULL,
  `Horario` VARCHAR(45) NULL,
  `Local` VARCHAR(45) NULL,
  `FrmCadEnventos_idFrmCadEnventos` INT NOT NULL,
  PRIMARY KEY (`idFrmDeventos`, `FrmCadEnventos_idFrmCadEnventos`),
  INDEX `fk_FrmDeventos_FrmCadEnventos1_idx` (`FrmCadEnventos_idFrmCadEnventos` ASC) VISIBLE,
  CONSTRAINT `fk_FrmDeventos_FrmCadEnventos1`
    FOREIGN KEY (`FrmCadEnventos_idFrmCadEnventos`)
    REFERENCES `Ifspdb`.`FrmCadEnventos` (`idFrmCadEnventos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ifspdb`.`FrmCadCurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ifspdb`.`FrmCadCurso` (
  `idFrmCadCurso` INT NOT NULL,
  `Curso` VARCHAR(45) NULL,
  `CargaHoraria` TIMESTAMP(5) NULL,
  `Horario` TIME NULL,
  `Professor` VARCHAR(45) NULL,
  `FrmConfComparecimeto_idFrmConfComparecimeto` INT NOT NULL,
  PRIMARY KEY (`idFrmCadCurso`),
  INDEX `fk_FrmCadCurso_FrmConfComparecimeto1_idx` (`FrmConfComparecimeto_idFrmConfComparecimeto` ASC) VISIBLE,
  CONSTRAINT `fk_FrmCadCurso_FrmConfComparecimeto1`
    FOREIGN KEY (`FrmConfComparecimeto_idFrmConfComparecimeto`)
    REFERENCES `Ifspdb`.`FrmConfComparecimeto` (`idFrmConfComparecimeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ifspdb`.`Cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ifspdb`.`Cadastro` (
  `idCadastro` INT NOT NULL,
  `Login` VARCHAR(45) NULL,
  `Senha` VARCHAR(10) NULL,
  `FrmDeventos_idFrmDeventos` INT NOT NULL,
  PRIMARY KEY (`idCadastro`, `FrmDeventos_idFrmDeventos`),
  INDEX `fk_Cadastro_FrmDeventos1_idx` (`FrmDeventos_idFrmDeventos` ASC) VISIBLE,
  CONSTRAINT `fk_Cadastro_FrmDeventos1`
    FOREIGN KEY (`FrmDeventos_idFrmDeventos`)
    REFERENCES `Ifspdb`.`FrmDeventos` (`idFrmDeventos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ifspdb`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ifspdb`.`Login` (
  `idLogin` INT NOT NULL,
  `Login` VARCHAR(45) NULL,
  `Senha` VARCHAR(45) NULL,
  `FrmDcursos_idFrmDcursos` INT NOT NULL,
  `FrmDcursos_CargaHoraria` TIMESTAMP(4) NOT NULL,
  `FrmDpalestras_idFrmDpalestras` INT NOT NULL,
  `FrmEmissaoCertificado_idFrmEmissaoCertificado` INT NOT NULL,
  `FrmCadEnventos_idFrmCadEnventos` INT NOT NULL,
  PRIMARY KEY (`idLogin`),
  INDEX `fk_Login_FrmDcursos_idx` (`FrmDcursos_idFrmDcursos` ASC, `FrmDcursos_CargaHoraria` ASC) VISIBLE,
  INDEX `fk_Login_FrmDpalestras1_idx` (`FrmDpalestras_idFrmDpalestras` ASC) VISIBLE,
  INDEX `fk_Login_FrmEmissaoCertificado1_idx` (`FrmEmissaoCertificado_idFrmEmissaoCertificado` ASC) VISIBLE,
  INDEX `fk_Login_FrmCadEnventos1_idx` (`FrmCadEnventos_idFrmCadEnventos` ASC) VISIBLE,
  CONSTRAINT `fk_Login_FrmDcursos`
    FOREIGN KEY (`FrmDcursos_idFrmDcursos` , `FrmDcursos_CargaHoraria`)
    REFERENCES `Ifspdb`.`FrmDcursos` (`idFrmDcursos` , `CargaHoraria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Login_FrmDpalestras1`
    FOREIGN KEY (`FrmDpalestras_idFrmDpalestras`)
    REFERENCES `Ifspdb`.`FrmDpalestras` (`idFrmDpalestras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Login_FrmEmissaoCertificado1`
    FOREIGN KEY (`FrmEmissaoCertificado_idFrmEmissaoCertificado`)
    REFERENCES `Ifspdb`.`FrmEmissaoCertificado` (`idFrmEmissaoCertificado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Login_FrmCadEnventos1`
    FOREIGN KEY (`FrmCadEnventos_idFrmCadEnventos`)
    REFERENCES `Ifspdb`.`FrmCadEnventos` (`idFrmCadEnventos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
